spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/LOCAPI_DB  # postgres вместо localhost
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  kafka:
    bootstrap-servers: kafka:9092  # kafka вместо localhost
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: locapi-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

validator:
  max-time-gap-ms: 300000
  max-speed-kmh: 300.0
  max-coord-jump-meters: 500.0

jwt:
  secret: mySuperSecretKey12345678901234567890cnsbcbvmn123213c12312312
  access:
    lifetime: 900000  # 15 минут
  refresh:
    lifetime: 2592000000  # 30 дней

topic: "snapshots"

logging:
  level:
    root: INFO
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access.intercept: TRACE
    org.springframework.security.authentication: TRACE

    org.springframework.boot.context.config: DEBUG
    org.springframework.core.env: DEBUG

    com.example: DEBUG

server:
  address: 0.0.0.0
  port: 8080